# Use the official .NET SDK image based on Debian Bookworm
FROM mcr.microsoft.com/dotnet/sdk:8.0.303 AS build

# Install necessary build tools
RUN apt-get update && apt-get install -y clang gcc libc6-dev libunwind-dev zlib1g-dev

# Set the entrypoint to be the dotnet CLI
ENTRYPOINT ["dotnet"]

#install az cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash